# Generated by Django 5.2.12 on 2026-03-22 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_size_remove_product_image_and_more'),
        ('reviews', '0002_alter_comment_product_alter_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='feedback_type',
            field=models.CharField(choices=[('quality', 'Chất lượng sản phẩm'), ('price', 'Giá cả'), ('shipping', 'Vấn đề giao hàng'), ('size', 'Kích thước/Size'), ('service', 'Chăm sóc khách hàng'), ('other', 'Khác')], default='quality', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
