# Generated by Django 5.2.13 on 2026-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='transaction_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='note',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
